### ISSUE TITLE
Missing dependency declaration

### ISSUE THREAD

**Issue by mudrd8mz** [andrewhancox/filter_databasetagcloud#2]
The filter depends on the presence of the other block: https://github.com/andrewhancox/filter_databasetagcloud/blob/86d6b2ef0afd4e7434b6824e81dbeb81f3036e83/filter.php#L32

But this dependency is not defined in the version.php file - see https://docs.moodle.org/dev/version.php

It is easy to get stuck on an error screen if the admin installs just this filter plugin.

**Comment by andrewhancox** [comment]
Fixed

**Comment by mudrd8mz** [comment]
No it's not. Have you actually tried to install it on a clean Moodle installation? Your version.php now declares dependency on `block_databasebookmarks` which (1) is not what that line refers to, and (2) does not exist.
