### ISSUE TITLE
Too simple placeholder pattern

### ISSUE THREAD

**Issue by mudrd8mz** [andrewhancox/filter_databasetagcloud#4]
Currently the filter uses the following regex to define the placeholder for the filter: `'/databasetagcloud_field_[0-9]+/'`

It looks like too simple pattern to me. And I could imagine it can eventually break other places in the HTML (such as HTML tags attributes) where such a text would eventually appear.

What about something slightly more complex and less probably to appear on its own, such as

```
{{DATABASETAGCLOUD_FIELD_42}}
```

**Comment by andrewhancox** [comment]
I think we'd be unlucky for someone to create an id or class that matches this and since the module is already in production it would be difficult to change.
